version: "3"

services:
  db:
    container_name: subsquid_db
    image: postgres:16
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"