manifestVersion: subsquid.io/v0.1
name: gs-explorer-statemine
version: 1
description: |-
  Giant Squid Explorer for Statemine chain
build:

deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN:
        statemine
    cmd: [ "node", "lib/main" ]
  api:
    cmd: [ "npx", "squid-graphql-server", "--dumb-cache", "in-memory", "--dumb-cache-ttl", "1000", "--dumb-cache-size", "100", "--dumb-cache-max-age", "1000" ]

scale:
  addons:
     postgres:
         storage: 50G
         profile: small